window.interviewData = [
  {
    id: "compute",
    title: "1. Compute (EC2, Lambda, Auto Scaling)",
    questions: [
      { id: 1, question: "Explain EC2 instance types and when to use each family.", answer: "<p>EC2 instance families are purpose-built for different workloads:</p><ul><li><strong>General Purpose (M, T series):</strong> Balanced CPU/memory. T3/T4g for burstable workloads (dev/test), M6i/M7g for production web servers and microservices.</li><li><strong>Compute Optimized (C series):</strong> High-performance processors. C6i/C7g for gaming, scientific modeling, HPC, high-traffic web servers.</li><li><strong>Memory Optimized (R, X, z series):</strong> Large memory-to-CPU ratio. R6i for in-memory databases (Redis, SAP), X2i for large SAP/Oracle workloads.</li><li><strong>Storage Optimized (I, D, H series):</strong> High I/O. I3/I4i for NoSQL databases needing local NVMe SSD.</li><li><strong>Accelerated Computing (P, G, Trn, Inf series):</strong> GPU/custom chips. P4/G5 for ML training/inference, Inf2 for cost-efficient inference.</li><li><strong>Graviton (any family with 'g' suffix):</strong> ARM-based, 20-40% better price/performance.</li></ul>" },
      { id: 2, question: "Difference between On-Demand, Reserved, Spot, and Savings Plans.", answer: "<p><strong>On-Demand:</strong> Pay per second, no commitment. Use for unpredictable workloads.</p><p><strong>Reserved Instances (RI):</strong> 1 or 3-year commitment. Up to 72% discount. Use for steady-state workloads. Standard RI for specific instance type; Convertible RI for flexibility.</p><p><strong>Savings Plans:</strong> Commitment to $/hr of usage (not specific instance). Compute Savings Plans cover EC2, Fargate, Lambda — most flexible. EC2 Savings Plans for 66% discount on specific instance families.</p><p><strong>Spot:</strong> Use spare AWS capacity at up to 90% discount. Can be interrupted with 2-min warning. Use for fault-tolerant, stateless, checkpointing workloads (batch, ML training, CI/CD).</p>" },
      { id: 3, question: "Explain EC2 Auto Scaling groups and scaling policies.", answer: "<p>Auto Scaling Groups (ASG) automatically adjust EC2 capacity:</p><ul><li><strong>Target Tracking:</strong> Maintain a specific metric (e.g., keep CPU at 60%). Simplest to configure. AWS automatically adds/removes instances.</li><li><strong>Step Scaling:</strong> Define steps — add 2 instances when CPU > 70%, add 5 when CPU > 90%. More control over scaling increments.</li><li><strong>Scheduled Scaling:</strong> Pre-scale before known load (e.g., scale up at 8 AM weekdays, down at 8 PM).</li><li><strong>Predictive Scaling:</strong> ML-based — analyzes historical patterns and proactively scales before demand increases.</li></ul><p>Warm pools pre-initialize stopped instances for faster scale-out.</p>" },
      { id: 4, question: "What is AWS Lambda and when would you choose it over EC2?", answer: "<p>Lambda is a serverless function execution service that runs code in response to events without managing servers. Choose Lambda when:</p><ul><li>Workload is event-driven (S3 upload, API call, SQS message)</li><li>Execution is short-lived (&lt;15 minutes per invocation)</li><li>Traffic is spiky or intermittent (pay only when invoked)</li><li>Zero-operations preference — no patching, no capacity planning</li></ul><p>Choose EC2 when: long-running processes, stateful apps, specific OS/hardware requirements, sustained high CPU workloads where EC2 is cheaper, or when Lambda cold start latency is unacceptable.</p>" },
      { id: 5, question: "Explain Lambda concurrency, cold starts, and provisioned concurrency.", answer: "<p><strong>Concurrency:</strong> Number of Lambda function instances running simultaneously. Default limit: 1000 per region. Reserve concurrency to throttle a function or guarantee capacity.</p><p><strong>Cold start:</strong> First invocation initializes the execution environment (download code, start runtime). Adds 100ms–2s latency. Worse for JVM/large runtimes, minimal for Go/Python.</p><p><strong>Provisioned Concurrency:</strong> Pre-initializes execution environments, eliminating cold starts. Billed even when idle. Use for latency-sensitive applications (payment processing, real-time APIs).</p>" },
      { id: 6, question: "Explain EC2 placement groups.", answer: "<p>Placement groups control how EC2 instances are physically placed:</p><ul><li><strong>Cluster:</strong> Instances in same rack. Ultra-low latency, high network throughput (100 Gbps). Use for HPC, tightly-coupled distributed computing. Single point of failure.</li><li><strong>Spread:</strong> Each instance on separate hardware rack. Maximum fault isolation. Up to 7 instances per AZ per group. Use for small critical databases.</li><li><strong>Partition:</strong> Instances spread across logical partitions, each partition on different hardware. For large distributed systems (Hadoop, Kafka, Cassandra) where partial rack failure should not affect all replicas.</li></ul>" },
      { id: 7, question: "What is the difference between vertical and horizontal scaling?", answer: "<p><strong>Vertical Scaling (Scale Up):</strong> Increase instance size (t3.medium → m6i.4xlarge). Simple, no application changes needed. Limited by largest instance size, requires downtime to resize in most cases, single point of failure.</p><p><strong>Horizontal Scaling (Scale Out):</strong> Add more instances. No upper limit, highly available, no downtime. Requires stateless application design (sessions in ElastiCache, files in S3). Auto Scaling Groups automate this. The preferred pattern in cloud architecture.</p>" },
      { id: 8, question: "Explain EC2 instance metadata and IMDSv2.", answer: "<p>EC2 Instance Metadata Service (IMDS) provides information about the running instance (IP, IAM role credentials, AMI ID, user data) at <code>http://169.254.169.254/latest/meta-data/</code>.</p><p><strong>IMDSv2 (Instance Metadata Service v2):</strong> Session-oriented, requires a PUT request to get a token before metadata queries. Protects against SSRF attacks where an attacker tricks the instance into leaking IAM credentials via metadata. Enforce IMDSv2 via instance configuration or SCP policy. IMDSv1 should be disabled in production.</p>" },
      { id: 9, question: "What are EC2 User Data and Launch Templates?", answer: "<p><strong>User Data:</strong> Shell scripts or cloud-init directives that run at instance first boot. Used to install software, configure services, join domains, or register with orchestration tools.</p><p><strong>Launch Templates:</strong> Versioned EC2 configuration (AMI, instance type, security groups, user data, key pair, IAM role). Reusable across Auto Scaling Groups, EC2 Fleet, and Spot Fleet. Support multiple versions with a default. Preferred over Launch Configurations (which are immutable and deprecated).</p>" },
      { id: 10, question: "Explain Lambda event source mappings and destinations.", answer: "<p><strong>Event Source Mappings:</strong> Allow Lambda to poll from event sources and invoke your function in batches. Sources: SQS, Kinesis Data Streams, DynamoDB Streams, Kafka (MSK). Configure batch size, batch window, and bisect-on-error to control failure handling. Failed batches go to SQS DLQ or Lambda destination.</p><p><strong>Lambda Destinations:</strong> Route successful/failed invocations to another service (SQS, SNS, EventBridge, another Lambda). Used for asynchronous invocations to handle success/failure flows without polling.</p>" }
    ]
  },
  {
    id: "networking",
    title: "2. Networking (VPC, Route 53, CloudFront)",
    questions: [
      { id: 11, question: "Explain AWS VPC and its core components.", answer: "<p>A Virtual Private Cloud (VPC) is a logically isolated virtual network in AWS. Core components:</p><ul><li><strong>Subnets:</strong> Subdivisions of VPC CIDR (public subnets have route to IGW, private do not)</li><li><strong>Internet Gateway (IGW):</strong> Allows public subnet resources to reach the internet</li><li><strong>NAT Gateway:</strong> Allows private subnet resources to reach the internet (outbound only)</li><li><strong>Route Tables:</strong> Control traffic routing between subnets and to/from internet</li><li><strong>Security Groups:</strong> Stateful instance-level firewall</li><li><strong>Network ACLs:</strong> Stateless subnet-level firewall</li><li><strong>VPC Endpoints:</strong> Private connectivity to AWS services without internet</li></ul><img src='assets/aws_vpc_architecture.png' alt='VPC Architecture' style='width:100%;max-width:600px;border-radius:8px;margin:16px 0;border:1px solid var(--border-color);'>" },
      { id: 12, question: "Difference between Security Groups and NACLs.", answer: "<p><strong>Security Groups (SG):</strong></p><ul><li>Stateful: return traffic is automatically allowed</li><li>Applied to instances/ENIs (not subnets)</li><li>Allow rules only (no explicit deny)</li><li>Evaluated as a whole (all rules evaluated)</li></ul><p><strong>Network ACLs:</strong></p><ul><li>Stateless: must explicitly allow return traffic in both directions</li><li>Applied to subnets</li><li>Allow AND deny rules</li><li>Rules evaluated in order (lowest rule number first, first match wins)</li><li>Default NACL allows all traffic; custom NACLs deny all by default</li></ul>" },
      { id: 13, question: "Explain VPC Peering vs AWS Transit Gateway.", answer: "<p><strong>VPC Peering:</strong> Direct 1:1 connection between two VPCs (same or different accounts/regions). No transitive routing (A↔B, B↔C doesn't mean A↔C). Low latency, no bandwidth limits, no extra cost per GB. Scales poorly with many VPCs (N² connections).</p><p><strong>Transit Gateway (TGW):</strong> Hub-and-spoke network transit hub. Connect hundreds of VPCs and on-prem networks through a single gateway. Supports transitive routing. Centralized route tables for traffic control. Higher setup complexity but scales linearly. Supports inter-region peering.</p>" },
      { id: 14, question: "Explain AWS Direct Connect vs VPN.", answer: "<p><strong>AWS Direct Connect:</strong> Dedicated private network connection from your data center to AWS. Consistent network performance (no internet variability), low latency, up to 100 Gbps. Higher cost, longer setup time (weeks to months). Use for: large data transfers, consistent latency-sensitive workloads, hybrid cloud.</p><p><strong>Site-to-Site VPN:</strong> IPSec tunnel over the internet. Quick setup (minutes), lower cost, but variable latency and lower bandwidth. Use for: DR/backup connectivity, smaller bandwidth needs, when Direct Connect isn't yet available.</p>" },
      { id: 15, question: "Explain Amazon Route 53 routing policies.", answer: "<p>Route 53 routing policies:</p><ul><li><strong>Simple:</strong> Single record, single value. No health checks. Basic DNS.</li><li><strong>Weighted:</strong> Distribute traffic by percentage (10% canary / 90% stable).</li><li><strong>Latency:</strong> Route to the region with lowest latency for the user. Ideal for global apps.</li><li><strong>Failover:</strong> Active-passive. Route to secondary if primary health check fails.</li><li><strong>Geolocation:</strong> Route based on user's geographic location. Content localization, compliance.</li><li><strong>Geoproximity:</strong> Route based on distance, with bias to shift traffic between regions.</li><li><strong>Multi-value Answer:</strong> Return up to 8 healthy records. Client-side load balancing.</li></ul>" },
      { id: 16, question: "Explain Amazon CloudFront and its use cases.", answer: "<p>CloudFront is AWS's global Content Delivery Network (CDN) with 400+ edge locations. It caches content at the edge, reducing latency and origin load.</p><p><strong>Use cases:</strong></p><ul><li>Static asset delivery (images, JS, CSS) from S3</li><li>Dynamic API acceleration (lower latency via AWS backbone)</li><li>Video streaming (HLS, DASH) with media packaging</li><li>DDoS protection via AWS Shield Standard (free) at edge</li><li>WAF integration for application firewall at edge</li><li>Lambda@Edge and CloudFront Functions for request/response manipulation at edge</li></ul>" },
      { id: 17, question: "What are VPC Endpoints and PrivateLink?", answer: "<p><strong>Gateway Endpoints:</strong> Free. Private access to S3 and DynamoDB without internet/NAT. Add a route table entry pointing to the endpoint.</p><p><strong>Interface Endpoints (PrivateLink):</strong> ENI in your VPC with a private IP. Access AWS services (SSM, ECR, Secrets Manager) or partner/customer services privately. Requires DNS resolution. Billed per hour and per GB processed. Eliminates need for NAT Gateway for AWS API calls in private subnets.</p><p><strong>Security benefit:</strong> Traffic never leaves the AWS network.</p>" },
      { id: 18, question: "Explain AWS Global Accelerator.", answer: "<p>Global Accelerator provides two static anycast IP addresses that route traffic to your application via the AWS global network (instead of the public internet). Benefits: 60% improvement in availability, reduced latency for global users (traffic enters AWS network at the nearest edge location), instant failover across regions (30-second health check intervals), and static IPs (no DNS propagation delays). Use for TCP/UDP workloads needing global routing — unlike CloudFront which is HTTP-only and caches.</p>" },
      { id: 19, question: "Explain Elastic Load Balancing — ALB, NLB, GLB.", answer: "<p><strong>ALB (Application Load Balancer):</strong> Layer 7. HTTP/HTTPS/gRPC. Path-based, host-based, header-based routing. Supports authentication (Cognito/OIDC), WAF, Lambda targets, weighted target groups (canary). Use for web apps and microservices.</p><p><strong>NLB (Network Load Balancer):</strong> Layer 4. TCP/UDP/TLS. Ultra-low latency, millions of RPS. Static IP per AZ, client IP preservation, PrivateLink support. Use for real-time gaming, VoIP, financial trading.</p><p><strong>GLB (Gateway Load Balancer):</strong> Layer 3. Transparent bump-in-the-wire for network appliances (firewalls, IDS/IPS). Distributes traffic to appliances and returns to original destination.</p>" },
      { id: 20, question: "How do you design a highly available, multi-AZ VPC architecture?", answer: "<p>Best practice multi-AZ VPC design:</p><ul><li><strong>3 AZs minimum</strong> for production (us-east-1 has 6)</li><li><strong>Per-AZ subnets:</strong> Public subnet (ALB, NAT GW), Private subnet (EC2, EKS), Database subnet (RDS, ElastiCache)</li><li><strong>NAT Gateway per AZ</strong> — avoid cross-AZ NAT traffic charges and single-AZ failure</li><li><strong>ALB spanning all AZs</strong> — routes to healthy targets in any AZ</li><li><strong>RDS Multi-AZ</strong> — synchronous standby in second AZ</li><li><strong>Security Groups</strong> chained by role (ALB-SG → App-SG → DB-SG)</li><li><strong>VPC Flow Logs</strong> → S3/CloudWatch for network audit</li></ul>" }
    ]
  },
  {
    id: "storage",
    title: "3. Storage (S3, EBS, EFS, Glacier)",
    questions: [
      { id: 21, question: "Explain Amazon S3 storage classes and when to use each.", answer: "<p>S3 storage classes (cost decreases, retrieval time increases):</p><ul><li><strong>Standard:</strong> Frequent access. Low latency. Most expensive. Use for active data.</li><li><strong>Intelligent-Tiering:</strong> Automatically moves objects between access tiers. Use for unknown access patterns. Small monitoring fee per object.</li><li><strong>Standard-IA (Infrequent Access):</strong> Lower storage cost, retrieval fee. Use for backups, DR copies accessed monthly.</li><li><strong>One Zone-IA:</strong> Same as IA but single AZ only. 20% cheaper. Use for recreatable data (thumbnails, transcoded video).</li><li><strong>Glacier Instant Retrieval:</strong> Archive with millisecond retrieval. Quarterly access.</li><li><strong>Glacier Flexible Retrieval:</strong> Minutes to hours retrieval. Annual access.</li><li><strong>Glacier Deep Archive:</strong> Cheapest. 12-hour retrieval. Compliance archiving (7-year retention).</li></ul>" },
      { id: 22, question: "Explain S3 security — bucket policies, ACLs, and Block Public Access.", answer: "<p><strong>Bucket Policies:</strong> Resource-based JSON policies attached to buckets. Grant/deny access to principals (other accounts, services, specific IAM roles). Support condition keys (IP, VPC endpoint, MFA, time).</p><p><strong>ACLs (Legacy):</strong> Object/bucket-level grants. Predefined grants (READ, WRITE). AWS recommends disabling ACLs (bucket owner enforced mode) and using policies instead.</p><p><strong>Block Public Access:</strong> 4 settings that override all policies and ACLs to prevent public access. Enable at account level to prevent accidental public exposure of any bucket. First line of defense. Enable S3 Access Analyzer to detect buckets with cross-account or public access.</p>" },
      { id: 23, question: "Explain S3 replication — CRR and SRR.", answer: "<p><strong>Cross-Region Replication (CRR):</strong> Automatically replicates objects to a bucket in a different AWS region. Use for: compliance (data sovereignty), disaster recovery, reduced latency for global users. Versioning must be enabled on both buckets.</p><p><strong>Same-Region Replication (SRR):</strong> Replicates within the same region. Use for: log aggregation, live staging environments with production data. Replication is asynchronous. Existing objects are NOT replicated by default (use S3 Batch Operations for backfill).</p>" },
      { id: 24, question: "Explain Amazon EBS volume types.", answer: "<p>EBS volume types:</p><ul><li><strong>gp3 (General Purpose SSD):</strong> 3000 IOPS baseline, up to 16000 IOPS independently provisioned. Use for most workloads. Cost-effective default.</li><li><strong>gp2:</strong> IOPS linked to size (3 IOPS/GB). Legacy — migrate to gp3.</li><li><strong>io2/io2 Block Express:</strong> Up to 256,000 IOPS. Sub-millisecond latency. Use for databases (Oracle, SAP HANA) requiring highest IOPS consistency. 99.999% durability.</li><li><strong>st1 (Throughput HDD):</strong> High sequential throughput. Use for big data, log processing (Kafka data disks).</li><li><strong>sc1 (Cold HDD):</strong> Lowest cost. Infrequent sequential access. Use for cold archival data on disk.</li></ul>" },
      { id: 25, question: "Explain Amazon EFS and when to use it over EBS.", answer: "<p>EFS is a fully managed, elastic NFS file system accessible by multiple EC2 instances and containers simultaneously (ReadWriteMany). Key features: auto-scales with data, Standard and IA storage classes, performance modes (General Purpose vs Max I/O), throughput modes (Bursting, Provisioned, Elastic). Use EFS when: multiple EC2 instances must share files, CMS shared content, ML training datasets, lift-and-shift NFS workloads. Use EBS when: single instance needs high-IOPS block storage (databases) — EBS outperforms EFS for single-instance I/O.</p>" },
      { id: 26, question: "Explain S3 lifecycle policies and object versioning.", answer: "<p><strong>Versioning:</strong> Preserves all versions of an object. Deletion creates a delete marker instead of removing the object. Enables recovery from accidental deletion or overwrites. Required for S3 replication and Object Lock.</p><p><strong>Lifecycle Policies:</strong> Automated rules to transition or expire objects: <code>Transition</code> actions move objects between storage classes (e.g., Standard → IA after 30 days, IA → Glacier after 90 days). <code>Expiration</code> actions delete objects or delete previous versions. Reduces cost by automatically tiering aging data.</p>" },
      { id: 27, question: "Explain S3 performance optimization.", answer: "<p>S3 performance tips:</p><ul><li><strong>Multipart Upload:</strong> Required for objects &gt;5GB, recommended for &gt;100MB. Parallel uploads, retry failed parts independently. Use Transfer Acceleration + multipart for cross-region uploads.</li><li><strong>Byte-range fetch:</strong> Download only part of an object in parallel (like multipart for downloads).</li><li><strong>S3 prefix:</strong> S3 supports 3500 PUT/5500 GET requests/second per prefix. Distribute objects across prefixes for high-throughput workloads.</li><li><strong>S3 Transfer Acceleration:</strong> Routes uploads through CloudFront edge locations for faster uploads from distant regions.</li><li><strong>S3 Express One Zone:</strong> Single-digit millisecond latency for latency-sensitive workloads.</li></ul>" },
      { id: 28, question: "What is Amazon S3 Object Lock?", answer: "<p>S3 Object Lock prevents objects from being deleted or overwritten for a fixed retention period — implementing WORM (Write Once, Read Many) storage. Modes:</p><ul><li><strong>Governance Mode:</strong> Users with special IAM permission can override or delete. Less strict.</li><li><strong>Compliance Mode:</strong> No one (including root user) can delete the object until retention expires. Meets SEC 17a-4, FINRA, HIPAA requirements.</li></ul><p><strong>Legal Hold:</strong> Indefinite lock regardless of retention date. Use for litigation holds. S3 Object Lock requires versioning to be enabled.</p>" },
      { id: 29, question: "Explain AWS Storage Gateway.", answer: "<p>Storage Gateway connects on-premises environments to AWS cloud storage. Types:</p><ul><li><strong>S3 File Gateway:</strong> NFS/SMB access to S3. Files appear as objects in S3. On-prem apps write files, Gateway uploads to S3.</li><li><strong>FSx File Gateway:</strong> Local cache of FSx for Windows File Server for on-prem SMB access.</li><li><strong>Volume Gateway:</strong> iSCSI block storage backed by S3. Cached mode (frequently accessed in cache, rest in S3) or Stored mode (all data on-prem, async backup to S3).</li><li><strong>Tape Gateway:</strong> Virtual tape library backed by S3/Glacier. Drop-in replacement for physical tape backup solutions.</li></ul>" },
      { id: 30, question: "How would you design a cost-effective S3 data lake architecture?", answer: "<p>Cost-effective S3 data lake design:</p><ul><li><strong>Storage tiering:</strong> Hot data in S3 Standard, warm data transitions to S3-IA after 30 days, cold to Glacier after 90 days via lifecycle policies</li><li><strong>Compression:</strong> Store data in columnar formats (Parquet, ORC) — 10x storage reduction vs CSV</li><li><strong>Partitioning:</strong> Partition by date/region — Athena scans only relevant partitions, reducing query cost</li><li><strong>Intelligent-Tiering:</strong> For unpredictable access patterns (analytics workloads)</li><li><strong>S3 Inventory:</strong> Monitor storage usage and plan transitions</li><li><strong>Requester Pays:</strong> For shared datasets where consumers pay for data access costs</li></ul>" }
    ]
  },
  {
    id: "databases",
    title: "4. Databases (RDS, Aurora, DynamoDB, ElastiCache)",
    questions: [
      { id: 31, question: "Explain Amazon RDS and when to choose it over EC2-hosted databases.", answer: "<p>RDS is a managed relational database service supporting MySQL, PostgreSQL, MariaDB, Oracle, SQL Server, and Db2. Choose RDS for: automated backups (35-day retention), automated patching, Multi-AZ failover, read replicas, easy scaling, and no OS management. Choose EC2-hosted databases when: you need specific DB engine versions not supported by RDS, custom kernel/storage configuration, or database features only available in self-managed setups. The operational savings of RDS typically outweigh the loss of control for most production workloads.</p>" },
      { id: 32, question: "Explain Amazon Aurora and its advantages over standard RDS.", answer: "<p>Aurora is AWS's cloud-native relational database — MySQL and PostgreSQL compatible with enterprise performance:</p><ul><li><strong>Storage:</strong> Distributed, self-healing 6-way replicated storage across 3 AZs automatically. No storage management needed.</li><li><strong>Performance:</strong> 5x faster than MySQL, 3x than PostgreSQL on same hardware</li><li><strong>Read scaling:</strong> Up to 15 read replicas with sub-10ms replication lag</li><li><strong>Aurora Serverless v2:</strong> Scales ACUs (Aurora Capacity Units) in fractions of a second based on load — ideal for variable workloads</li><li><strong>Aurora Global Database:</strong> Sub-second cross-region replication for global read access and DR</li></ul>" },
      { id: 33, question: "Explain Amazon DynamoDB and its key design concepts.", answer: "<p>DynamoDB is a serverless, fully managed NoSQL key-value and document database. Key concepts:</p><ul><li><strong>Partition Key:</strong> Determines which partition the item is stored in. Choose high-cardinality, evenly distributed keys to avoid hot partitions.</li><li><strong>Sort Key:</strong> Allows range queries within a partition. Together with partition key forms a composite primary key.</li><li><strong>GSI (Global Secondary Index):</strong> Alternative partition/sort key. Queries across all partitions.</li><li><strong>LSI (Local Secondary Index):</strong> Alternative sort key on same partition. Must be defined at table creation.</li><li><strong>On-demand vs Provisioned:</strong> On-demand for unpredictable traffic; Provisioned + Auto Scaling for steady-state cost optimization.</li></ul>" },
      { id: 34, question: "Explain DynamoDB consistency models.", answer: "<p><strong>Eventually Consistent Reads (default):</strong> Response may not reflect recent writes (propagation delay across replicas). Lower cost and higher throughput. Use for non-critical reads.</p><p><strong>Strongly Consistent Reads:</strong> Returns the most up-to-date data, reflecting all prior writes. Costs 2x read capacity units. Higher latency. Use for financial data, inventory counts, anywhere stale data causes issues.</p><p><strong>DynamoDB Transactions:</strong> All-or-nothing operations across up to 100 items / 4MB. Use <code>TransactWriteItems</code> for ACID operations across multiple items (e.g., transfer funds).</p>" },
      { id: 35, question: "Explain Amazon ElastiCache — Redis vs Memcached.", answer: "<p><strong>Redis:</strong> Feature-rich, persistent, supports data structures (sorted sets, pub/sub, streams), replication with failover, cluster mode (horizontal sharding), Multi-AZ with automatic failover. Use for: session storage, leaderboards, rate limiting, pub/sub messaging, distributed locks.</p><p><strong>Memcached:</strong> Simple key-value cache, multithreaded, no persistence, no replication, no data structures. Simpler and faster for pure caching use cases. Horizontal scaling via adding nodes (no cluster mode complexity).</p><p>Choose Redis for most new workloads due to its richer feature set. Memcached for simple object caching at massive scale where Redis features aren't needed.</p>" },
      { id: 36, question: "Explain RDS Multi-AZ vs Read Replicas.", answer: "<p><strong>Multi-AZ:</strong> High availability mechanism. Synchronous replication to standby in another AZ. Standby is NOT a read endpoint — it's purely for failover. Automatic failover (1-2 min) during primary failure. FQDN automatically switches to standby. Use for production databases where downtime must be minimized.</p><p><strong>Read Replicas:</strong> Performance scaling mechanism. Asynchronous replication. Each replica has its own endpoint — your application must use it explicitly. Up to 15 replicas. Can be in different regions for geographic distribution. Can be promoted to standalone DB for migration/DR. Use for read-heavy workloads (reporting, analytics).</p>" },
      { id: 37, question: "Explain DynamoDB DynamoDB Accelerator (DAX).", answer: "<p>DAX is an in-memory cache purpose-built for DynamoDB that provides microsecond read latency. It's a fully managed, write-through cache cluster deployed in your VPC. Application uses the DAX client (drop-in replacement for DynamoDB client). Cache hit returns item from memory in microseconds; cache miss fetches from DynamoDB and populates cache. Benefits: reduces DynamoDB read load, dramatically reduces latency for popular items. Limitations: doesn't support strongly consistent reads (pass through to DynamoDB) and not suitable for write-heavy workloads.</p>" },
      { id: 38, question: "How do you handle database migrations in AWS with minimal downtime?", answer: "<p>AWS Database Migration Service (DMS) enables live migrations:</p><ol><li><strong>Full load:</strong> DMS migrates all existing data from source to target</li><li><strong>CDC (Change Data Capture):</strong> DMS continuously replicates changes during migration so source remains live</li><li><strong>Cutover:</strong> Stop application writes to source, let CDC drain, switch connection string to target</li></ol><p><strong>Schema Conversion Tool (SCT):</strong> Converts schema from one engine to another (Oracle → Aurora PostgreSQL). Identifies and assists with code that needs manual conversion. Total downtime can be reduced to minutes using this approach.</p>" },
      { id: 39, question: "Explain Amazon Redshift and when to use it.", answer: "<p>Redshift is AWS's cloud data warehouse optimized for analytical queries over massive datasets (petabyte-scale). Uses columnar storage (up to 10x query performance over row-based), data compression, and massively parallel processing (MPP). Redshift Serverless auto-scales automatically. Redshift Spectrum queries S3 directly without loading data. Use Redshift for: business intelligence (Tableau, QuickSight), ad-hoc analytical queries, aggregation over billions of rows. Not for OLTP (use RDS/Aurora) or document queries (use DynamoDB).</p>" },
      { id: 40, question: "Explain Aurora Global Database for disaster recovery.", answer: "<p>Aurora Global Database provides cross-region replication with &lt;1 second lag, using dedicated replication infrastructure (not database replication). One primary region (read/write) and up to 5 secondary regions (read-only). In case of regional disaster, a secondary region can be promoted to primary in &lt;1 minute (RPO ~1 second, RTO ~1 minute). Cross-region read replicas reduce latency for global users. Use for: global SaaS applications, compliance (data residency with local reads), disaster recovery with low RTO/RPO requirements.</p>" }
    ]
  },
  {
    id: "security",
    title: "5. Security, Identity & Compliance",
    questions: [
      { id: 41, question: "Explain AWS IAM — policies, roles, and best practices.", answer: "<p>IAM controls who can do what to which AWS resources:</p><ul><li><strong>Identity-based policies:</strong> Attached to IAM users, groups, or roles. Define what the principal can do.</li><li><strong>Resource-based policies:</strong> Attached to resources (S3, KMS, SQS). Define who can access the resource.</li><li><strong>Permission boundaries:</strong> Set max permissions an identity can have — even if policies grant more.</li><li><strong>Service Control Policies (SCP):</strong> Organization-level guardrails applied to accounts.</li></ul><p><strong>Best practices:</strong> Never use root account. Use roles for services (not access keys). Enable MFA. Apply least privilege. Use IAM Access Analyzer to find overly permissive policies. Rotate credentials regularly.</p>" },
      { id: 42, question: "Explain AWS Organizations and Service Control Policies.", answer: "<p>AWS Organizations allows managing multiple AWS accounts centrally. Organizational Units (OUs) group accounts hierarchically. SCPs (Service Control Policies) act as guardrails — they restrict what actions IAM identities in member accounts can perform, even if their IAM policies allow it. SCPs cannot grant permissions. Example SCP: deny <code>ec2:RunInstances</code> for non-Graviton instance types to enforce cost efficiency, or deny all actions outside approved regions for data sovereignty. Combined with AWS Control Tower for landing zone automation and compliance.</p>" },
      { id: 43, question: "Explain AWS KMS and key types.", answer: "<p>AWS Key Management Service (KMS) is a managed service for creating and controlling encryption keys:</p><ul><li><strong>AWS managed keys:</strong> Created by AWS for each service (aws/s3, aws/rds). Automatically rotated annually. You can view but not manage.</li><li><strong>Customer managed keys (CMK):</strong> You create, manage, and rotate. Supports key policies, grants, automatic rotation. Required for fine-grained access control and cross-account usage.</li><li><strong>AWS CloudHSM:</strong> Dedicated Hardware Security Module. FIPS 140-2 Level 3 validated. Full control of key material. Required for strict compliance (PCI-DSS Level 1). Higher cost than KMS.</li></ul>" },
      { id: 44, question: "Explain AWS WAF and Shield.", answer: "<p><strong>AWS WAF (Web Application Firewall):</strong> Layer 7 protection. Deploy in front of CloudFront, ALB, API Gateway. Blocks OWASP Top 10 attacks (SQL injection, XSS, etc.), rate limits, geo-blocking. Managed Rule Groups from AWS and AWS Marketplace. Use for: web application security, bot control, rate limiting per IP.</p><p><strong>AWS Shield Standard:</strong> Free, automatic DDoS protection for all AWS services at L3/L4 (SYN floods, UDP reflection).</p><p><strong>AWS Shield Advanced:</strong> $3000/month. Enhanced DDoS protection, 24/7 DDoS Response Team, cost protection (AWS refunds charges caused by DDoS scaling events), near real-time visibility.</p>" },
      { id: 45, question: "Explain Amazon GuardDuty.", answer: "<p>GuardDuty is a continuous threat detection service using machine learning to identify unexpected and potentially malicious activity. It analyzes: VPC Flow Logs, DNS logs, CloudTrail management events, CloudTrail S3 data events, and EKS audit logs (with runtime monitoring). Findings are categorized (Backdoor, CryptoMining, Recon, Trojan, UnauthorizedAccess). Integrate with Security Hub for centralized findings and EventBridge for automated remediation (e.g., isolate compromised EC2). Enable organization-wide via AWS Organizations delegated admin.</p>" },
      { id: 46, question: "Explain AWS Secrets Manager vs Systems Manager Parameter Store.", answer: "<p><strong>Secrets Manager:</strong> Purpose-built for secrets. Automatic rotation (calls Lambda function to rotate RDS, Redshift, DocumentDB credentials). Cross-account access. Replication across regions. Cost: $0.40/secret/month + $0.05 per 10K API calls. Use for: database credentials, API keys, OAuth tokens where rotation is needed.</p><p><strong>SSM Parameter Store:</strong> Hierarchical key-value store. Standard tier free (4KB max, 10K parameters). Advanced tier: $0.05/parameter/month (8KB, higher API rate, parameter policies/TTL). No automatic rotation. Use for: configuration values, feature flags, non-rotating secrets. Integrates natively with CloudFormation and EC2 User Data.</p>" },
      { id: 47, question: "Explain Amazon Cognito.", answer: "<p>Cognito provides authentication, authorization, and user management for web and mobile apps:</p><ul><li><strong>User Pools:</strong> User directory with sign-up/sign-in. Issues JWT tokens. Supports MFA, social identity providers (Google, Facebook), SAML federation. Provides hosted UI for authentication pages.</li><li><strong>Identity Pools (Federated Identities):</strong> Exchange tokens (Cognito, Google, SAML, OpenID) for temporary AWS credentials (via STS AssumeRoleWithWebIdentity). Enables fine-grained access to AWS resources (different IAM role per user group).</li></ul><p>Use Cognito User Pools for application authentication and Identity Pools to grant users direct AWS resource access.</p>" },
      { id: 48, question: "Explain AWS Config and compliance automation.", answer: "<p>AWS Config continuously records resource configuration changes and evaluates them against managed or custom rules. Config Rules can check: 'Is MFA enabled on root?', 'Are all EBS volumes encrypted?', 'Do all instances have required tags?'. Non-compliant resources are flagged.</p><p>Remediation: AWS Config integrates with SSM Automation documents for auto-remediation (e.g., automatically enable S3 block public access when a non-compliant bucket is detected). Conformance Packs bundle multiple rules for compliance frameworks (HIPAA, PCI-DSS, CIS). Config data feeds AWS Security Hub for centralized compliance view.</p>" },
      { id: 49, question: "Explain AWS Security Hub.", answer: "<p>Security Hub provides a comprehensive view of security alerts and compliance status across AWS accounts. It aggregates findings from: GuardDuty, Inspector, Macie, IAM Access Analyzer, Systems Manager, Firewall Manager, and third-party tools. Runs continuous CIS AWS Foundations Benchmark and PCI-DSS checks. Supports multi-account aggregation via Organizations. Integrates with EventBridge for automated remediation workflows. Provides a security score to track improvement over time.</p>" },
      { id: 50, question: "Explain defense-in-depth architecture in AWS.", answer: "<p>Defense-in-depth layers in AWS:</p><ol><li><strong>Edge:</strong> CloudFront + WAF + Shield to block attacks before they reach your infrastructure</li><li><strong>Network:</strong> VPC with public/private subnets, NACLs, Security Groups, VPC Flow Logs</li><li><strong>Compute:</strong> IMDSv2, no SSH (use SSM Session Manager), patching via Systems Manager Patch Manager</li><li><strong>Application:</strong> Cognito for authentication, Secrets Manager for credentials, least-privilege IAM</li><li><strong>Data:</strong> S3 encryption + Object Lock, KMS for all data at rest, TLS in transit</li><li><strong>Detection:</strong> GuardDuty, Config, CloudTrail, Security Hub</li><li><strong>Response:</strong> EventBridge + Lambda automated remediation</li></ol>" }
    ]
  },
  {
    id: "architecture",
    title: "6. Architecture & Well-Architected Framework",
    questions: [
      { id: 51, question: "Explain the AWS Well-Architected Framework.", answer: "<p>The Well-Architected Framework provides best practices across six pillars:</p><ul><li><strong>Operational Excellence:</strong> Run and monitor systems, continually improve processes (IaC, CI/CD, runbooks, post-mortems)</li><li><strong>Security:</strong> Protect information and systems (IAM, encryption, detective controls)</li><li><strong>Reliability:</strong> Workload ability to recover from failures (Multi-AZ, backups, chaos engineering)</li><li><strong>Performance Efficiency:</strong> Use resources efficiently (right instance types, serverless, caching)</li><li><strong>Cost Optimization:</strong> Avoid unnecessary costs (Spot, Reserved, right-sizing)</li><li><strong>Sustainability:</strong> Minimize environmental impact (efficient code, Graviton, right-sizing)</li></ul><img src='assets/aws_well_architected.png' alt='Well-Architected Framework' style='width:100%;max-width:600px;border-radius:8px;margin:16px 0;border:1px solid var(--border-color);'>" },
      { id: 52, question: "Explain the Shared Responsibility Model.", answer: "<p>AWS and customers share security responsibilities:</p><p><strong>AWS's responsibility ('Security OF the Cloud'):</strong> Physical data center security, hardware, hypervisor, managed service infrastructure (RDS patching, Lambda runtime).</p><p><strong>Customer's responsibility ('Security IN the Cloud'):</strong> Guest OS patching (for EC2), application code security, IAM user management, data encryption, network traffic protection, security groups configuration.</p><p><strong>Shared:</strong> Patch management (AWS patches RDS, you patch EC2), configuration management, awareness and training. The line moves based on service type: IaaS (EC2) — more customer responsibility; SaaS (Rekognition) — more AWS responsibility.</p>" },
      { id: 53, question: "Design a serverless application architecture on AWS.", answer: "<p>Serverless reference architecture:</p><ul><li><strong>API layer:</strong> Amazon API Gateway (REST or HTTP API) for request routing, authentication, throttling</li><li><strong>Compute:</strong> AWS Lambda for business logic — auto-scales, pay per invocation</li><li><strong>Database:</strong> DynamoDB (serverless, auto-scaling) or Aurora Serverless v2</li><li><strong>Caching:</strong> ElastiCache or DynamoDB DAX for hot data</li><li><strong>Events:</strong> EventBridge for decoupled event routing, SQS for async processing</li><li><strong>Auth:</strong> Cognito User Pools for user authentication</li><li><strong>Storage:</strong> S3 for files, pre-signed URLs for direct uploads</li><li><strong>Monitoring:</strong> CloudWatch + X-Ray for observability</li></ul><img src='assets/aws_serverless_architecture.png' alt='Serverless Architecture' style='width:100%;max-width:600px;border-radius:8px;margin:16px 0;border:1px solid var(--border-color);'>" },
      { id: 54, question: "Explain event-driven architecture patterns in AWS.", answer: "<p>Event-driven architecture decouples services through asynchronous events:</p><ul><li><strong>Amazon SQS:</strong> Message queue for point-to-point async communication. Guarantees at-least-once delivery. Standard (best-effort ordering) vs FIFO (exactly-once, ordered).</li><li><strong>Amazon SNS:</strong> Pub/Sub fan-out. One message → multiple subscribers (SQS, Lambda, HTTP, email). Use for multi-subscriber notification patterns.</li><li><strong>SNS + SQS fan-out pattern:</strong> SNS topic fans out to multiple SQS queues (different consumers process same event independently).</li><li><strong>Amazon EventBridge:</strong> Event bus with content-based routing rules. First-class integration with 90+ AWS services and SaaS. Supports event replay, schema registry, global endpoints.</li><li><strong>Kinesis Data Streams:</strong> Real-time streaming data ingestion. Multiple consumers, ordered within shards.</li></ul>" },
      { id: 55, question: "Explain the SAGA pattern for distributed transactions.", answer: "<p>The SAGA pattern manages distributed transactions across microservices without two-phase commit:</p><p><strong>Choreography-based SAGA:</strong> Each service publishes an event after completing its step. Next service listens and processes. Simpler, but hard to track state. Compensating transactions undo previous steps on failure.</p><p><strong>Orchestration-based SAGA:</strong> A central orchestrator (AWS Step Functions) tells each service what to do, tracks state, and handles failures with compensating transactions. More complex but easier to observe and debug. Recommended for complex multi-step processes (order processing: reserve inventory → charge payment → ship order).</p>" },
      { id: 56, question: "Explain CQRS and Event Sourcing in AWS.", answer: "<p><strong>CQRS (Command Query Responsibility Segregation):</strong> Separate read and write models. Writes go to a primary database, reads from optimized read models (DynamoDB, Elasticsearch, Redis). Enables independent scaling of reads and writes.</p><p><strong>Event Sourcing:</strong> Store all state changes as an immutable sequence of events (in DynamoDB Streams or Kinesis). Current state derived by replaying events. Benefits: full audit trail, replay capability, event-driven integrations. Example: DynamoDB as event store → DynamoDB Streams triggers Lambda → Lambda updates read models (Elasticsearch, Redis).</p>" },
      { id: 57, question: "Explain Strangler Fig pattern for migration.", answer: "<p>Strangler Fig gradually replaces a monolith with microservices without big-bang rewrite:</p><ol><li>Put an API Gateway or ALB in front of the monolith (facade)</li><li>Identify a feature to extract (e.g., user authentication)</li><li>Build the new microservice independently</li><li>Route traffic for that feature to the new service via the facade</li><li>Validate, then repeat for next feature</li><li>Monolith shrinks (strangled) as more features migrate</li></ol><p>In AWS: ALB path-based routing directs /auth/* to the new Lambda/ECS service while /* still goes to the monolith EC2 instances.</p>" },
      { id: 58, question: "Explain Circuit Breaker pattern.", answer: "<p>The Circuit Breaker prevents cascading failures when a downstream service is failing:</p><ul><li><strong>Closed state:</strong> Normal operation. Requests pass through.</li><li><strong>Open state:</strong> After N consecutive failures, circuit opens. Requests fail immediately (fallback response) without calling failing service. Gives the service time to recover.</li><li><strong>Half-open state:</strong> After timeout, allows a test request. If successful, close circuit; if fails, re-open.</li></ul><p>In AWS: Implement in service mesh (Istio/App Mesh), AWS App Mesh, or application code (Resilience4j, Hystrix). Amazon Route 53 health checks + failover routing implement circuit breaking at DNS level.</p>" },
      { id: 59, question: "Design a disaster recovery strategy for a critical AWS application.", answer: "<p>DR strategies by RTO/RPO (cost increases with lower RTO/RPO):</p><ul><li><strong>Backup & Restore:</strong> RTO: hours. RPO: hours. Cheapest. Backup to S3/Glacier, restore from scratch. For non-critical systems.</li><li><strong>Pilot Light:</strong> RTO: tens of minutes. Core services (DB) always running in DR region, app servers off. Start app servers on failover.</li><li><strong>Warm Standby:</strong> RTO: minutes. Scaled-down version running in DR region. Scale up on failover. Use Aurora Global Database for DB sync.</li><li><strong>Active-Active (Multi-Region):</strong> RTO: near zero. Both regions serving traffic. Route 53 latency/failover routing. Highest cost.</li></ul>" },
      { id: 60, question: "How do you design for failure in AWS?", answer: "<p>Designing for failure principles:</p><ul><li><strong>Everything fails:</strong> Assume any component can fail at any time. Design for graceful degradation.</li><li><strong>Multi-AZ by default:</strong> Deploy all components across &ge;2 AZs</li><li><strong>Stateless application tier:</strong> No session state on EC2 (use ElastiCache/DynamoDB) so any instance can serve any request</li><li><strong>Retry with exponential backoff:</strong> AWS SDK does this automatically. Add jitter to prevent thundering herd.</li><li><strong>Dead Letter Queues:</strong> Catch and preserve failed messages for reprocessing</li><li><strong>Health checks everywhere:</strong> ALB, Route 53, Auto Scaling all use health checks to route around failure</li><li><strong>Chaos Engineering:</strong> Simulate failures with AWS Fault Injection Service</li></ul>" }
    ]
  },
  {
    id: "devops",
    title: "7. DevOps & CI/CD",
    questions: [
      { id: 61, question: "Explain AWS CodePipeline and its stages.", answer: "<p>CodePipeline is a fully managed CI/CD service that automates release pipelines. Stages:</p><ul><li><strong>Source:</strong> CodeCommit, GitHub, S3, ECR — triggers pipeline on change</li><li><strong>Build:</strong> CodeBuild (managed build containers), runs tests, produces artifacts</li><li><strong>Test:</strong> CodeBuild, third-party tools, device farm testing</li><li><strong>Deploy:</strong> CodeDeploy (EC2/ECS/Lambda), CloudFormation, Elastic Beanstalk, EKS</li></ul><p>Pipelines support manual approval actions, parallel stages, and cross-region/cross-account actions. Integrates natively with other AWS services and popular tools (Jenkins, GitHub Actions).</p>" },
      { id: 62, question: "Explain Infrastructure as Code — CloudFormation vs Terraform.", answer: "<p><strong>AWS CloudFormation:</strong> AWS-native IaC service. YAML/JSON templates. Stacks group related resources with full lifecycle management. Drift detection, change sets, nested stacks, StackSets for multi-account deployment. Deep AWS service coverage on day one. No separate state management (AWS manages state). Free service (pay for resources created).</p><p><strong>Terraform:</strong> Open-source, multi-cloud IaC. HCL language. Large provider ecosystem. Remote state management (S3 + DynamoDB). Terraform Cloud/Enterprise features (RBAC, policy). Better for multi-cloud or when team already knows Terraform. Slightly behind CloudFormation on newest AWS services.</p>" },
      { id: 63, question: "Explain AWS CodeDeploy deployment strategies.", answer: "<p>CodeDeploy supports multiple deployment strategies:</p><ul><li><strong>All-at-once:</strong> Deploys to all instances simultaneously. Fastest but causes downtime. Use only for dev/test.</li><li><strong>Rolling:</strong> Deploys to a few instances at a time. Reduces availability temporarily. Configurable batch size.</li><li><strong>Rolling with additional batch:</strong> Maintains full capacity during deployment by launching extra instances first.</li><li><strong>Blue/Green:</strong> Traffic switches from old (blue) to new (green) instances after validation. Instant rollback by switching back. For EC2 and Lambda.</li><li><strong>Canary (Lambda/ECS):</strong> Shift small % of traffic, validate, then complete rollout. Example: Canary10Percent5Minutes.</li></ul>" },
      { id: 64, question: "Explain AWS Systems Manager capabilities.", answer: "<p>Systems Manager is the operational hub for managing AWS resources at scale:</p><ul><li><strong>Session Manager:</strong> Browser/CLI shell access to EC2 without SSH/bastion hosts. Audited, IAM-controlled, no inbound ports needed.</li><li><strong>Patch Manager:</strong> Automate OS and application patching. Patch baselines, maintenance windows, compliance reporting.</li><li><strong>Parameter Store:</strong> Hierarchical configuration storage, encrypted with KMS.</li><li><strong>Run Command:</strong> Execute scripts on fleets of instances without SSH.</li><li><strong>Automation:</strong> Runbooks (SSM Documents) for operational tasks — remediation, provisioning, AMI creation.</li><li><strong>Inventory:</strong> Collect instance metadata (software, config, network) for compliance.</li></ul>" },
      { id: 65, question: "Explain AWS CDK vs CloudFormation.", answer: "<p>CDK (Cloud Development Kit) is a framework that generates CloudFormation templates using familiar programming languages (TypeScript, Python, Java, Go, C#). Benefits over raw CloudFormation:</p><ul><li>Reusable constructs (L1: raw CFN, L2: opinionated with defaults, L3: complete patterns)</li><li>Type safety and IDE completion</li><li>Loops, conditions, and abstractions that would be verbose in YAML</li><li>Test your infrastructure with familiar unit testing tools (Jest, Pytest)</li><li>Share infrastructure patterns as npm/PyPI packages</li></ul><p>CDK apps synthesize to CloudFormation — same deployment engine, no additional state management.</p>" },
      { id: 66, question: "Explain container image build and push pipeline for ECR.", answer: "<p>Typical CI/CD pipeline for container images:</p><ol><li>Developer pushes code to Git</li><li>GitHub Actions / CodePipeline triggers</li><li>CodeBuild runs: <code>docker build</code>, unit tests, <code>trivy image scan</code> (block on CRITICAL)</li><li>Sign image: <code>cosign sign</code> with OIDC identity from CI</li><li>Push to ECR: <code>aws ecr get-login-password | docker push</code></li><li>Update image tag in GitOps repo (Helm values.yaml or Kustomize overlay)</li><li>ArgoCD/Flux detects change and deploys to EKS</li></ol><p>ECR image scanning (enhanced, via Inspector) continuously scans for new CVEs after push.</p>" },
      { id: 67, question: "What is AWS Elastic Beanstalk and when should you use it?", answer: "<p>Elastic Beanstalk is a PaaS (Platform as a Service) that abstracts infrastructure management. You upload application code and Beanstalk handles: EC2 provisioning, Auto Scaling, ALB setup, OS patching, CloudWatch integration. Supports Java, .NET, Node.js, Python, Ruby, PHP, Go, Docker.</p><p>Use Beanstalk when: Small team without DevOps expertise, quick deployment of standard web app, migrating from traditional hosting. Avoid for: complex multi-service architectures (use ECS/EKS), when you need fine-grained infrastructure control, or when the opinionated setup conflicts with your needs.</p>" },
      { id: 68, question: "Explain AWS Step Functions.", answer: "<p>Step Functions is a serverless orchestration service for multi-step workflows as state machines. States: Task (invoke Lambda/SDK), Choice (branching), Wait, Parallel, Map (iterate over array), Pass, Succeed, Fail.</p><p><strong>Standard Workflows:</strong> Exactly-once, auditable history, up to 1 year duration. For long-running business processes (order fulfillment, ETL pipelines).</p><p><strong>Express Workflows:</strong> At-least-once, high-throughput, up to 5 minutes. For high-volume event processing (IoT telemetry).</p><p>Use Step Functions for SAGA orchestration, ML training pipelines, and replacing complex Lambda function chains.</p>" },
      { id: 69, question: "Explain Amazon EventBridge.", answer: "<p>EventBridge is a serverless event bus connecting AWS services, custom applications, and SaaS providers. Features:</p><ul><li><strong>Event rules:</strong> Content-based routing (route events matching specific patterns to targets)</li><li><strong>Targets:</strong> 20+ AWS services (Lambda, SQS, Step Functions, ECS, API Gateway, etc.)</li><li><strong>Event Bus:</strong> Default (AWS service events), custom, and partner buses (Zendesk, Datadog)</li><li><strong>Schema Registry:</strong> Discover and store event schemas, generate code bindings</li><li><strong>Pipes:</strong> Point-to-point integrations with filtering, enrichment, and transformation</li><li><strong>Global endpoints:</strong> Multi-region event delivery for HA</li></ul>" },
      { id: 70, question: "How do you implement GitOps for AWS infrastructure?", answer: "<p>GitOps for AWS infrastructure:</p><ul><li><strong>Terraform + Atlantis:</strong> Atlantis runs <code>terraform plan</code> on PRs and comments the diff. Merge PR to apply. Full auditability in Git history.</li><li><strong>CDK Pipelines:</strong> CDK pipeline self-mutates — the pipeline code itself is in CDK and deploys via CodePipeline.</li><li><strong>AWS Proton:</strong> Template-based self-service platform for infrastructure provisioning. Platform team creates templates, devs provision from catalog.</li><li><strong>Drift detection:</strong> AWS Config detects drift from desired state. Terraform Cloud has drift detection. Alert and auto-remediate via Lambda.</li><li><strong>OPA for Terraform:</strong> Conftest or Sentinel enforces policy on Terraform plans before apply.</li></ul>" }
    ]
  },
  {
    id: "monitoring",
    title: "8. Monitoring, Logging & Observability",
    questions: [
      { id: 71, question: "Explain Amazon CloudWatch — metrics, logs, and alarms.", answer: "<p>CloudWatch is the core AWS observability service:</p><ul><li><strong>Metrics:</strong> Time-series data from AWS services (EC2 CPU, RDS connections) and custom metrics via PutMetricData API. Standard resolution (1 min), high resolution (1 sec, higher cost).</li><li><strong>Logs:</strong> CloudWatch Logs Insights for interactive log querying with SQL-like syntax. Log groups and streams. Metric Filters extract metrics from log data.</li><li><strong>Alarms:</strong> Evaluate metric against threshold over a period. States: OK, ALARM, INSUFFICIENT_DATA. Actions: SNS, Auto Scaling, EC2 (stop/terminate). Composite alarms combine multiple alarms.</li><li><strong>Dashboards:</strong> Custom operational dashboards with cross-account and cross-region support.</li></ul>" },
      { id: 72, question: "Explain AWS X-Ray for distributed tracing.", answer: "<p>X-Ray provides distributed tracing for AWS workloads. Instrument your application with the X-Ray SDK or ADOT (OpenTelemetry). X-Ray traces requests through: API Gateway, Lambda, EC2/ECS, RDS, DynamoDB, SQS, SNS. Features:</p><ul><li><strong>Service Map:</strong> Visual graph of your application's services and their connections with latency and error metrics</li><li><strong>Trace details:</strong> Waterfall view showing each segment/subsegment with timing</li><li><strong>Groups and sampling rules:</strong> Sample 5% of traffic normally, 100% for errors</li><li><strong>Annotations:</strong> Index custom key-value pairs for filtering traces</li></ul>" },
      { id: 73, question: "Explain AWS CloudTrail.", answer: "<p>CloudTrail records all API calls made in your AWS account — the audit log of 'who did what, when, from where'. Captures: API calls from CLI, console, SDK, services. Stores events in S3 (90-day default in Event History, unlimited with a Trail). Management events (control plane: CreateInstance) are logged by default. Data events (S3 GetObject, Lambda Invoke) must be explicitly enabled — higher volume.</p><p><strong>CloudTrail Insights:</strong> Detects unusual API activity (spike in EC2 terminations) using ML. Enable multi-region trails and log file integrity validation for compliance.</p>" },
      { id: 74, question: "Explain Amazon OpenSearch Service for log analytics.", answer: "<p>Amazon OpenSearch Service (formerly Elasticsearch Service) is a managed distributed search and analytics engine. Use cases: log analytics (ELK stack), full-text search, security analytics (SIEM), business intelligence.</p><p><strong>Typical log pipeline:</strong> CloudWatch Logs → CloudWatch Subscription Filter → Lambda → OpenSearch. Or: Fluent Bit → Kinesis Data Firehose → OpenSearch. OpenSearch Dashboards (formerly Kibana) for visualization. OpenSearch Serverless auto-scales without capacity planning. Use for: complex log queries, full-text search, security dashboards (SIEM), and forensic analysis.</p>" },
      { id: 75, question: "What is Amazon CloudWatch Container Insights?", answer: "<p>CloudWatch Container Insights collects, aggregates, and visualizes metrics and logs from containerized apps on EKS, ECS, and Kubernetes. Deployed as ADOT Collector or CloudWatch Agent DaemonSet. Provides pre-built dashboards for: cluster health, node CPU/memory, Pod performance, service error rates. Metrics: pod_cpu_utilization, pod_memory_utilization, pod_network_rx_bytes. Integrates with CloudWatch Alarms for auto-scaling triggers and alerting. Enables per-namespace cost tracking when combined with custom metrics.</p>" },
      { id: 76, question: "Explain Amazon Managed Grafana and Prometheus.", answer: "<p><strong>Amazon Managed Service for Prometheus (AMP):</strong> Serverless Prometheus-compatible service. No capacity management. EKS clusters send metrics via remote_write. Compatible with all PromQL queries and existing Prometheus dashboards. Ingestion and query scale independently. Uses IAM for access control.</p><p><strong>Amazon Managed Grafana (AMG):</strong> Fully managed Grafana. Pre-integrated with AMP, CloudWatch, X-Ray, Athena as data sources. Enterprise features (SAML, LDAP) included. Team-scoped workspaces. SLA-backed availability. Costs: per active user seat vs. self-managed infrastructure cost.</p>" },
      { id: 77, question: "How do you centralize logs from multiple AWS accounts?", answer: "<p>Multi-account centralized logging architecture:</p><ul><li><strong>Option 1 — CloudWatch cross-account:</strong> CloudWatch Logs in member accounts subscribe to Kinesis Data Streams or Firehose in a central logging account via resource policies</li><li><strong>Option 2 — S3 centralization:</strong> Each account's CloudTrail, ALB access logs, VPC Flow Logs write to S3 in central logging account (using bucket policies for cross-account writes)</li><li><strong>Option 3 — Fluent Bit:</strong> Fluent Bit on EC2/EKS in each account sends to centralized OpenSearch or Loki</li><li><strong>AWS Security Lake:</strong> Automatically centralize security logs (CloudTrail, VPC Flow, Route 53) from all Organization accounts into OCSF format in S3</li></ul>" },
      { id: 78, question: "Explain SLIs, SLOs, and SLAs in AWS context.", answer: "<p><strong>SLI (Service Level Indicator):</strong> The measurable metric. Defined using CloudWatch metrics or Synthetics canaries. Example: 'p99 API latency as measured by ALB TargetResponseTime metric.'</p><p><strong>SLO (Service Level Objective):</strong> Internal target. Example: '99.9% of API requests complete in &lt;500ms.' Monitor with CloudWatch alarm on error budget burn rate.</p><p><strong>SLA (Service Level Agreement):</strong> Customer-facing commitment with penalties. Example: AWS's own SLA for RDS is 99.95% monthly uptime.</p><p>AWS has SLAs for all major services. Track your own SLOs using CloudWatch Metrics and Alarms, or AWS Application Signals.</p>" },
      { id: 79, question: "Explain AWS Application Signals.", answer: "<p>AWS Application Signals (preview) is a new capability for automatic SLO tracking. It auto-instruments applications using ADOT/OpenTelemetry and calculates RED metrics (Rate, Error, Duration) per service. Displays a service map automatically without manual instrumentation. Sets SLOs directly in the console and tracks error budget burn. Powered by CloudWatch and X-Ray. Reduces time-to-observability for new services.</p>" },
      { id: 80, question: "How do you set up alerting and on-call for AWS workloads?", answer: "<p>End-to-end alerting pipeline:</p><ol><li><strong>Detection:</strong> CloudWatch Alarm triggers when metric breaches threshold for N evaluation periods</li><li><strong>Notification:</strong> Alarm → SNS topic → multiple subscribers: PagerDuty (for on-call paging), Slack (via Lambda webhook), email</li><li><strong>Triage:</strong> On-call engineer uses CloudWatch dashboards, Logs Insights, X-Ray to investigate</li><li><strong>Automation:</strong> EventBridge rule triggers Lambda for common auto-remediation (restart service, scale ASG)</li><li><strong>Suppression:</strong> Maintenance window silences alarms via SSM or composite alarm configuration</li><li><strong>Post-mortem:</strong> CloudTrail + CloudWatch Logs provide evidence for blameless post-mortems</li></ol>" }
    ]
  },
  {
    id: "migration",
    title: "9. Migration & Cost Optimization",
    questions: [
      { id: 81, question: "Explain the 6 R's of cloud migration strategy.", answer: "<p>The 6 R's framework for migrating applications to AWS:</p><ol><li><strong>Rehost (Lift & Shift):</strong> Move as-is to EC2/RDS. Fastest. Use AWS Application Migration Service (MGN). No optimization benefit immediately.</li><li><strong>Replatform (Lift, Tinker & Shift):</strong> Minor optimizations without code changes. EC2 → RDS, Tomcat → Elastic Beanstalk, self-managed MySQL → Aurora.</li><li><strong>Repurchase (Drop & Shop):</strong> Replace with SaaS (Salesforce, SAP, ServiceNow). No migration — drop existing and buy new.</li><li><strong>Refactor/Rearchitect:</strong> Redesign using cloud-native services (monolith → microservices, API Gateway + Lambda). Most expensive, highest benefit.</li><li><strong>Retire:</strong> Decommission — 20-30% of portfolio is often unused. Save cost immediately.</li><li><strong>Retain:</strong> Keep on-premises for now (regulatory, latency, recently upgraded).</li></ol>" },
      { id: 82, question: "Explain AWS Migration Hub and migration tools.", answer: "<p>AWS Migration Hub is the central place to track migration progress across all AWS migration tools:</p><ul><li><strong>AWS Application Discovery Service:</strong> Agentless or agent-based discovery of on-prem servers (CPU, memory, network, dependencies). Creates application dependency maps.</li><li><strong>AWS Application Migration Service (MGN):</strong> Automated lift-and-shift. Continuous block-level replication → cutover with minimal downtime. Replaces CloudEndure Migration.</li><li><strong>AWS Database Migration Service (DMS):</strong> Migrate databases to RDS/Aurora with CDC for minimal downtime.</li><li><strong>AWS DataSync:</strong> Accelerated data transfer (NFS, SMB, HDFS, S3, EFS) up to 10x faster than open-source tools.</li></ul>" },
      { id: 83, question: "Explain AWS Cost Explorer and cost optimization strategies.", answer: "<p>AWS Cost Explorer visualizes, understands, and manages AWS spending. Key features: 12 months of historical data, 12-month forecasts, resource-level cost breakdown, Reserved Instance and Savings Plans recommendations.</p><p><strong>Cost optimization strategies:</strong></p><ul><li>Right-size EC2 instances using Compute Optimizer recommendations</li><li>Purchase Savings Plans for predictable workloads (1-3 year commitment)</li><li>Use Spot Instances for stateless/fault-tolerant workloads</li><li>Enable S3 Intelligent-Tiering for unpredictable access</li><li>Identify and delete unattached EBS volumes, unused Elastic IPs, idle load balancers</li><li>Use Graviton instances for 20-40% savings</li></ul>" },
      { id: 84, question: "What is AWS Compute Optimizer?", answer: "<p>Compute Optimizer uses ML to analyze CloudWatch metrics and recommend right-sizing for EC2 instances, Auto Scaling groups, Lambda functions, EBS volumes, and ECS on Fargate. It shows: current vs recommended instance type, estimated monthly savings, and projected performance improvement. Recommendations are based on 14 days of utilization data. Enable in Organizations for fleet-wide recommendations. Findings include: over-provisioned (save money), under-provisioned (performance risk), and optimized.</p>" },
      { id: 85, question: "Explain AWS Trusted Advisor.", answer: "<p>Trusted Advisor provides real-time best practice recommendations across 5 categories:</p><ul><li><strong>Cost Optimization:</strong> Idle EC2/RDS, unassociated Elastic IPs, low-utilization instances</li><li><strong>Performance:</strong> High-utilization EC2, CDN usage, provisioned throughput</li><li><strong>Security:</strong> Open security groups, MFA on root, IAM use, exposed access keys</li><li><strong>Fault Tolerance:</strong> Multi-AZ RDS, S3 versioning, EBS snapshots</li><li><strong>Service Quotas:</strong> Approaching limits for key services</li></ul><p>Basic checks free; full access requires Business/Enterprise Support plan.</p>" },
      { id: 86, question: "Explain Spot Instance strategies for cost reduction.", answer: "<p>Maximizing Spot reliability while minimizing costs:</p><ul><li><strong>Instance diversification:</strong> Specify multiple instance types and AZs — reduces interruption probability. Karpenter and EC2 Fleet support this natively.</li><li><strong>Interruption handling:</strong> Use 2-minute interruption notice to checkpoint work, drain in-flight requests, save state to S3</li><li><strong>Mixed fleet:</strong> On-Demand baseline (30%) + Spot surge (70%) — Auto Scaling group with on-demand base</li><li><strong>Spot placement score:</strong> Find AZs with highest Spot availability for your instance types</li><li><strong>Use cases:</strong> CI/CD build agents (stateless), batch processing (checkpointing), Karpenter-managed EKS nodes</li></ul>" },
      { id: 87, question: "Explain AWS Savings Plans vs Reserved Instances.", answer: "<p><strong>Reserved Instances (RIs):</strong> Commit to specific instance type, region, and OS. Standard RI: 72% discount, no flexibility. Convertible RI: 66% discount, can change instance family/size/OS. Sell unused capacity in Reserved Instance Marketplace.</p><p><strong>Savings Plans:</strong> Commit to $/hr usage (not specific instances). Compute Savings Plans: 66% max discount, apply to EC2 (any family/size/region), Lambda, and Fargate. EC2 Savings Plans: 72% max discount, specific instance family, but flexible size/OS. Easier to manage than RIs — no need to track instance type inventory.</p><p><strong>Best practice:</strong> Use Compute Savings Plans as baseline, then add EC2 SPs or RIs for specific high-cost instance families.</p>" },
      { id: 88, question: "Explain AWS Cost Allocation Tags.", answer: "<p>Cost allocation tags are key-value pairs applied to AWS resources that allow cost allocation and tracking by business dimensions (team, project, environment, cost center). Two types: AWS-generated tags (aws:createdBy, aws:cloudformation:stack-name) and User-defined tags (team:payments, env:production). Activate tags in Cost Explorer (24-48 hour delay). Use with AWS Budgets: set budget per tag value and alert when exceeded. Enforce tagging compliance with AWS Config rule <code>required-tags</code> or SCP denying resource creation without required tags.</p>" },
      { id: 89, question: "What is AWS Budgets?", answer: "<p>AWS Budgets allows setting custom budgets and alerts on AWS cost and usage:</p><ul><li><strong>Cost budget:</strong> Alert when actual or forecasted cost exceeds threshold</li><li><strong>Usage budget:</strong> Alert on specific service usage (EC2 hours, S3 GB)</li><li><strong>Reservation/Savings Plans budget:</strong> Track RI utilization and coverage</li><li><strong>Budget Actions:</strong> Automated response to breaches — apply SCP to deny further spending, apply IAM policy, target Auto Scaling group</li></ul><p>Set up budgets per account, team (via tags), service, or region. Essential for multi-account cost governance with AWS Organizations.</p>" },
      { id: 90, question: "How do you optimize data transfer costs in AWS?", answer: "<p>Data transfer costs are often overlooked and can be significant:</p><ul><li><strong>Free data transfers:</strong> Data IN to AWS, within same AZ between EC2 and S3, within same region using PrivateLink</li><li><strong>Cross-AZ traffic:</strong> $0.01/GB each direction — use private IPs, co-locate frequently-communicating services in same AZ</li><li><strong>CloudFront:</strong> CloudFront origin fetch from S3 is free — serve from CloudFront to users instead of S3 directly</li><li><strong>VPC Endpoints:</strong> Eliminate NAT Gateway data processing charges ($0.045/GB) for S3/DynamoDB</li><li><strong>AWS Direct Connect:</strong> Lower data transfer rates for large sustained transfers vs internet</li><li><strong>S3 Transfer Acceleration:</strong> Only use when speed benefit justifies cost</li></ul>" }
    ]
  },
  {
    id: "analytics",
    title: "10. Data, Analytics & AI/ML",
    questions: [
      { id: 91, question: "Explain AWS data lake architecture.", answer: "<p>AWS data lake reference architecture:</p><ul><li><strong>Ingestion:</strong> AWS Glue (ETL), Kinesis Data Streams (real-time), DMS (databases), DataSync (on-prem), S3 Direct PUT</li><li><strong>Storage:</strong> Amazon S3 (multi-tier: raw, curated, analytics zones). Parquet/ORC format for analytics efficiency.</li><li><strong>Catalog:</strong> AWS Glue Data Catalog — central metadata repository. Glue Crawlers auto-discover schema.</li><li><strong>Processing:</strong> AWS Glue (serverless Spark ETL), EMR (managed Hadoop/Spark), Athena (serverless SQL)</li><li><strong>Analytics:</strong> Amazon Redshift Spectrum, QuickSight, SageMaker for ML</li><li><strong>Governance:</strong> AWS Lake Formation for fine-grained access control (column/row-level security)</li></ul>" },
      { id: 92, question: "Explain Amazon Kinesis services.", answer: "<p>Amazon Kinesis family for real-time data streaming:</p><ul><li><strong>Kinesis Data Streams:</strong> Durable, ordered streaming with multiple consumer support. Retention: 24 hours to 365 days. Shards = throughput unit (1MB/s in, 2MB/s out). Enhanced fan-out: 2MB/s per consumer per shard. Use for: real-time analytics, event sourcing.</li><li><strong>Kinesis Data Firehose:</strong> Fully managed delivery to S3, Redshift, OpenSearch, Splunk, HTTP endpoints. No shard management. Auto-scales. Built-in transformation with Lambda. Use for: log ingestion, ETL to S3.</li><li><strong>Kinesis Data Analytics:</strong> Serverless SQL or Apache Flink for real-time stream processing.</li></ul>" },
      { id: 93, question: "Explain AWS Glue and its components.", answer: "<p>AWS Glue is a serverless data integration (ETL) service:</p><ul><li><strong>Glue Data Catalog:</strong> Central metadata store for databases and tables. Used by Athena, Redshift Spectrum, EMR as a shared Hive Metastore.</li><li><strong>Glue Crawlers:</strong> Automatically discover data schema from S3, RDS, Redshift and update the catalog.</li><li><strong>Glue ETL Jobs:</strong> Serverless Apache Spark (or Python Shell) for data transformation. Auto-generated code from visual editor or write custom PySpark/Scala.</li><li><strong>Glue DataBrew:</strong> Visual data preparation (no-code) for cleaning and normalizing data.</li><li><strong>Glue Studio:</strong> Visual job design and monitoring for ETL workflows.</li></ul>" },
      { id: 94, question: "Explain Amazon Athena.", answer: "<p>Athena is a serverless, interactive query service that analyzes data in S3 using standard SQL. No infrastructure to manage — pay per query ($5 per TB scanned). Key optimizations: store data in columnar formats (Parquet/ORC) to reduce scan, partition tables by date/region (Athena only scans relevant partitions), compress data. Supports Athena Federated Query (query RDS, DynamoDB, HBase without moving data). Use Workgroups for cost control per team. Athena for Apache Spark enables big data processing without cluster management.</p>" },
      { id: 95, question: "Explain Amazon SageMaker.", answer: "<p>SageMaker is AWS's fully managed ML platform covering the entire ML lifecycle:</p><ul><li><strong>Studio:</strong> Unified IDE for ML (Jupyter-based)</li><li><strong>Data Wrangler:</strong> Data preparation and feature engineering (300+ built-in transforms)</li><li><strong>Feature Store:</strong> Centralized repository for reusable ML features</li><li><strong>Training:</strong> Managed distributed training with any framework (TensorFlow, PyTorch)</li><li><strong>Pipelines:</strong> CI/CD for ML workflows</li><li><strong>Model Registry:</strong> Version and manage trained models</li><li><strong>Endpoints:</strong> Deploy models as real-time APIs or batch transform jobs</li><li><strong>Clarify:</strong> Bias detection and model explainability</li></ul>" },
      { id: 96, question: "Explain Amazon Bedrock.", answer: "<p>Amazon Bedrock is a fully managed service for building generative AI applications using foundation models (FMs) from AI21 Labs, Anthropic (Claude), Meta (Llama), Stability AI, Amazon (Titan), and Mistral — all via a single API. Key features:</p><ul><li><strong>Knowledge Bases:</strong> RAG (Retrieval Augmented Generation) with your documents in S3 → OpenSearch Vector DB</li><li><strong>Agents:</strong> Multi-step reasoning agents that call your APIs (Lambda) to complete tasks</li><li><strong>Fine-tuning:</strong> Customize FMs with your own training data</li><li><strong>Model Evaluation:</strong> Compare model performance across tasks</li><li><strong>Data privacy:</strong> Your data never trains the underlying FM</li></ul>" },
      { id: 97, question: "Explain AWS Lake Formation.", answer: "<p>AWS Lake Formation provides centralized data lake security and governance built on top of S3 and the Glue Data Catalog. Features:</p><ul><li><strong>Fine-grained access control:</strong> Column-level and row-level security (cell-level security for specific data) on Glue catalog tables — applies to Athena, Redshift Spectrum, EMR, Glue queries</li><li><strong>Centralized permissions:</strong> Grant/revoke access to databases, tables, and columns across all data users</li><li><strong>Data filters:</strong> Row-level filtering (e.g., user only sees their region's data)</li><li><strong>Blueprints:</strong> Pre-built workflows for ingesting data from JDBC, log files, S3</li><li><strong>Governed Tables:</strong> ACID transactions on S3 data lake</li></ul>" },
      { id: 98, question: "Explain Amazon QuickSight.", answer: "<p>QuickSight is AWS's cloud-native business intelligence (BI) service for data visualization and dashboards. Key features:</p><ul><li><strong>SPICE:</strong> In-memory calculation engine for fast queries on large datasets without hitting source DB every time</li><li><strong>ML Insights:</strong> Anomaly detection, forecasting, and natural language queries (Q) built into dashboards</li><li><strong>Embedded analytics:</strong> Embed QuickSight dashboards in your application with row-level security per user</li><li><strong>Data sources:</strong> S3/Athena, Redshift, RDS, Aurora, SalesForce, Jira, and more</li><li><strong>Pricing:</strong> Per-user (author vs. reader pricing) — more cost-effective than Tableau/PowerBI at scale</li></ul>" },
      { id: 99, question: "Explain how to design a real-time analytics pipeline on AWS.", answer: "<p>Real-time analytics pipeline reference architecture:</p><ol><li><strong>Ingestion:</strong> IoT devices / applications → Kinesis Data Streams (ordered, durable)</li><li><strong>Processing:</strong> Kinesis Data Analytics for Apache Flink — windowed aggregations, anomaly detection in real-time</li><li><strong>Storage:</strong> Flink outputs to multiple sinks: Kinesis Firehose → S3 (for batch analytics), Amazon OpenSearch (for real-time dashboards), DynamoDB (for serving layer)</li><li><strong>Visualization:</strong> OpenSearch Dashboards for real-time operational dashboards, QuickSight for business metrics</li><li><strong>Alerting:</strong> CloudWatch + SNS when streaming metrics breach thresholds</li></ol>" },
      { id: 100, question: "What is AWS DataZone?", answer: "<p>AWS DataZone is a data management service for discovering, cataloging, sharing, and governing data across organizational boundaries. Key concepts:</p><ul><li><strong>Data Portals:</strong> Business-friendly interface for data consumers to discover and request access to datasets</li><li><strong>Domains:</strong> Organize data assets by business unit or data domain</li><li><strong>Data Assets:</strong> Publish datasets from S3, Glue, Redshift, RDS to the catalog</li><li><strong>Subscriptions:</strong> Data consumers request access; owners approve; DataZone automates IAM/Lake Formation permission grants</li><li><strong>Lineage:</strong> Track data origin and transformations</li></ul><p>Use for enterprise data mesh architectures where data ownership is distributed across teams.</p>" }
    ]
  },
  {
    id: "leadership",
    title: "11. Senior Architect Leadership",
    questions: [
      { id: 101, question: "How do you approach cloud architecture reviews?", answer: "<p>Structured architecture review process:</p><ol><li><strong>Understand requirements:</strong> Business goals, SLAs, compliance requirements, team size, budget constraints</li><li><strong>Well-Architected Review:</strong> Use AWS Well-Architected Tool to systematically evaluate all six pillars. Generates prioritized improvement plan.</li><li><strong>Document architecture:</strong> Architecture Decision Records (ADRs) capturing why specific choices were made</li><li><strong>Risk assessment:</strong> Identify single points of failure, security gaps, scaling bottlenecks</li><li><strong>Proof of concept:</strong> Validate assumptions with hands-on testing before committing to design</li><li><strong>Review cadence:</strong> Quarterly architecture reviews as requirements evolve</li></ol>" },
      { id: 102, question: "How do you evaluate AWS services for a new workload?", answer: "<p>Technology evaluation framework:</p><ul><li><strong>Build vs buy:</strong> Is this a differentiating capability (build) or commodity (use managed service)?</li><li><strong>Managed vs self-managed:</strong> Calculate total cost of ownership including operational burden. AWS managed services usually win when factoring in patching, scaling, HA, and operator expertise needed.</li><li><strong>Maturity and stability:</strong> GA services preferred over preview. Check service health history.</li><li><strong>Lock-in vs agility trade-off:</strong> Deep AWS service integration increases lock-in but provides faster delivery. Use abstraction layers (IaC, containers) to mitigate.</li><li><strong>Team capability:</strong> Can the team operate this service? What's the learning investment?</li><li><strong>Cost projection:</strong> Model cost at current and 10x scale.</li></ul>" },
      { id: 103, question: "How do you lead a cloud migration program?", answer: "<p>Cloud migration program leadership:</p><ol><li><strong>Portfolio assessment:</strong> Application Discovery Service to inventory all workloads, categorize by 6Rs</li><li><strong>Landing Zone:</strong> AWS Control Tower to set up multi-account structure, guardrails, networking baseline</li><li><strong>Migration waves:</strong> Start with low-risk workloads (retire/rehost) to build team confidence and tooling. Complex refactors last.</li><li><strong>Factory model:</strong> Repeatable playbooks for common migration patterns (Windows server, Java app, Oracle DB)</li><li><strong>Cloud Center of Excellence (CCoE):</strong> Central team provides guardrails, shared services, and support</li><li><strong>KPIs:</strong> Track: applications migrated/month, cloud cost savings, incident reduction</li></ol>" },
      { id: 104, question: "How do you manage multi-account AWS environments?", answer: "<p>Multi-account best practices:</p><ul><li><strong>AWS Organizations structure:</strong> Management account (billing only), Security account (audit, GuardDuty aggregation), Log Archive account (CloudTrail, Config centralization), Shared Services account (DNS, Active Directory, ECR), Workload accounts (one per environment per team)</li><li><strong>AWS Control Tower:</strong> Automates landing zone setup with Account Factory for new account provisioning</li><li><strong>SCPs:</strong> Organization-level guardrails (deny non-approved regions, enforce S3 block public access)</li><li><strong>AWS SSO (IAM Identity Center):</strong> Single sign-on across all accounts with SAML integration</li><li><strong>Cross-account access:</strong> IAM roles with cross-account trust, not IAM users</li></ul>" },
      { id: 105, question: "How do you implement FinOps practices in AWS?", answer: "<p>FinOps (Cloud Financial Operations) — bringing financial accountability to cloud spending:</p><ul><li><strong>Visibility:</strong> Enforce cost allocation tags, AWS Cost Explorer with resource-level granularity, Kubecost for container costs</li><li><strong>Allocation:</strong> Shared costs (networking, logging) distributed via showback/chargeback rules</li><li><strong>Optimization:</strong> Commitment-based discounts (Savings Plans), Spot for batch, right-sizing via Compute Optimizer</li><li><strong>Accountability:</strong> Team-level budgets with Budget Actions, weekly cost reviews in team standups</li><li><strong>Culture:</strong> Cloud cost in engineering decision-making. 'If this feature costs $X/month, is it worth it?' Engineers review Trusted Advisor and Cost Explorer for their services.</li></ul>" },
      { id: 106, question: "Explain the AWS Cloud Adoption Framework (CAF).", answer: "<p>AWS CAF guides organizations through cloud adoption across 6 perspectives:</p><ul><li><strong>Business:</strong> Align IT with business outcomes. Value realization roadmap.</li><li><strong>People:</strong> Organizational change management, skills, and culture transformation.</li><li><strong>Governance:</strong> Portfolio management, risk, compliance, data governance.</li><li><strong>Platform:</strong> Architecture standards, reference architectures, IaC practices.</li><li><strong>Security:</strong> IAM, VPC design, encryption, compliance, detective controls.</li><li><strong>Operations:</strong> Monitoring, incident management, change management, ITSM integration.</li></ul><p>CAF provides a structured approach vs. ad-hoc cloud adoption. AWS Partners use it for cloud transformation engagements.</p>" },
      { id: 107, question: "How do you govern cloud security at enterprise scale?", answer: "<p>Enterprise security governance:</p><ul><li><strong>Policy as code:</strong> SCPs for hard guardrails (prevent root key creation, enforce MFA), AWS Config for soft controls (detect non-compliant resources)</li><li><strong>Centralized security operations:</strong> AWS Security Hub aggregates findings from GuardDuty, Inspector, Macie, Config across all accounts</li><li><strong>Threat detection:</strong> GuardDuty Organization-wide, automated remediation via EventBridge + Lambda</li><li><strong>Privileged access:</strong> AWS IAM Identity Center + time-limited access (Break Glass procedures documented)</li><li><strong>Data protection:</strong> Macie for sensitive data discovery in S3, KMS CMKs with key policies, CloudTrail for auditability</li><li><strong>Vulnerability management:</strong> Amazon Inspector for EC2 and ECR image scanning continuously</li></ul>" },
      { id: 108, question: "How do you design for regulatory compliance (HIPAA, PCI-DSS, SOC2)?", answer: "<p>Compliance architecture patterns:</p><ul><li><strong>Account isolation:</strong> Dedicated accounts for in-scope workloads (PCI CDE, HIPAA PHI). Minimizes compliance scope.</li><li><strong>Encryption everywhere:</strong> KMS CMK for all data at rest, TLS 1.2+ in transit, certificate management via ACM</li><li><strong>Audit trail:</strong> CloudTrail all-region, all-service, immutable logs in S3 with Object Lock + MFA Delete</li><li><strong>Access control:</strong> MFA enforced via SCP, no root usage, IAM Access Analyzer for permission review</li><li><strong>Vulnerability management:</strong> Amazon Inspector continuous scanning, patching via SSM Patch Manager with compliance reporting</li><li><strong>BAA / agreements:</strong> AWS signs HIPAA BAA. Review AWS service compliance page for each service in scope.</li></ul>" },
      { id: 109, question: "What trade-offs do you consider in cloud architecture decisions?", answer: "<p>Common architectural trade-offs:</p><ul><li><strong>Managed vs control:</strong> RDS is managed (less operational burden) vs EC2-hosted (full control but high ops cost). Usually choose managed.</li><li><strong>Cost vs availability:</strong> Single-AZ RDS (50% cheaper) vs Multi-AZ (high availability). Production always Multi-AZ.</li><li><strong>Serverless vs containers:</strong> Lambda (no ops, pay-per-use, cold starts) vs ECS/EKS (full control, predictable cost at scale, complex ops).</li><li><strong>Consistency vs availability:</strong> DynamoDB eventual consistency (cheaper, faster) vs strong consistency (2x cost, higher latency).</li><li><strong>Build vs buy:</strong> Custom auth vs Cognito. Build only when Cognito limitations block key requirements.</li><li><strong>Speed vs technical debt:</strong> Quick hack vs clean architecture. Document debt and schedule paydown.</li></ul>" },
      { id: 110, question: "How do you communicate architecture to non-technical stakeholders?", answer: "<p>Communication strategies for technical architecture:</p><ul><li><strong>Business outcomes first:</strong> Lead with business impact (reduced downtime, 40% cost reduction, faster time to market), not technology choices</li><li><strong>Analogies:</strong> 'Auto Scaling is like hiring temporary staff for Black Friday, then letting them go' — relatable mental models</li><li><strong>Simplified diagrams:</strong> Business capability map vs technical architecture. Different view for executives vs engineers.</li><li><strong>Risk language:</strong> Translate technical risks to business risk (single point of failure → potential 4-hour revenue loss)</li><li><strong>Cost transparency:</strong> Show cost vs. risk trade-offs — let leadership make informed decisions</li><li><strong>Proof of concepts:</strong> Demo working prototypes instead of slideware when possible</li></ul>" }
    ]
  }
];
